### ISSUE TITLE
Dojo themes repository was wiped out.

### ISSUE THREAD

**Issue by szymon-musiol** [dojo/themes#1]
This repository was updated yesterday and now it is empty. Is this on purpose?

**Comment by agubler** [comment]
@netrounds-szymon Apologies we were in the process of relocating the Dojo 1 themes to a new repository [`@dojo/dijit-themes`](https://github.com/dojo/dijit-themes) so that this repository could be repurposed exclusively for Dojo 2 themes.

We should have added a README indicating this immediately, which I have now [added](https://github.com/dojo/themes/blob/master/README.md).

**Comment by szymon-musiol** [comment]
OK, thank you very much for help!
